import { PublicDataResponse } from './types.js';

export const fallbackData: PublicDataResponse = {
  business: {
    businessName: 'Balham Key Cutting',
    tagline: 'Fast, Reliable Key Duplication & Spare Keys in Balham',
    phone: '+44 7491 275560',
    whatsapp: '447491275560',
    email: 'info@balhamkeycutting.co.uk',
    address: '180 Balham High Road',
    area: 'Balham',
    city: 'London',
    postcode: 'SW12 9BW',
    latitude: 51.4442,
    longitude: -0.1528,
    googlePlaceId: '',
    websiteUrl: 'https://balhamkeycutting.co.uk',
    businessDescription: 'Balham Key Cutting (CoreTech) is an independent South London workshop providing fast, accurate, and reliable key duplication, high-security cutting, and electronic RFID fob cloning.',
    directionsHelp: 'Located at 180 Balham High Road (CoreTech, next to Costa Coffee), 2 min walk from Balham Tube & National Rail Station',
    socialLinks: {
      googleBusiness: '',
    },
  },
  services: [
    {
      id: 'svc-1',
      name: 'Key Duplication',
      shortDescription: 'Standard cylinder and pin tumbler keys copied quickly with high-accuracy duplication machinery.',
      fullDescription: 'We cut duplicates for standard front door keys, back doors, and padlocks while you wait.',
      icon: 'KeyRound',
      turnaround: '2 - 3 minutes',
      active: true,
      sortOrder: 1,
      features: ['Precision computer calibrated', 'Deburred and polished finish', 'Tested key profile blanks'],
    },
    {
      id: 'svc-2',
      name: 'House Keys',
      shortDescription: 'Yale, ERA, Union, and Euro cylinder keys cut accurately for residential tenants, landlords, and homeowners.',
      fullDescription: 'Complete selection of high-grade brass and nickel residential key blanks.',
      icon: 'Home',
      turnaround: '2 - 5 minutes',
      active: true,
      sortOrder: 2,
      features: ['Euro cylinder keys', 'Standard rim latch keys', 'Patio and sliding door keys'],
    },
    {
      id: 'svc-3',
      name: 'Spare Keys',
      shortDescription: 'Convenient backup keys for cleaners, guests, family members, or emergency lockboxes.',
      fullDescription: 'Never get locked out in Balham again. Keep affordable spare sets with neighbours or family.',
      icon: 'CopyCheck',
      turnaround: '2 - 3 minutes',
      active: true,
      sortOrder: 3,
      features: ['Multi-pack discount available', 'Colour coded key tags available', 'Fast counter service'],
    },
    {
      id: 'svc-4',
      name: 'Office & Business Keys',
      shortDescription: 'Commercial key blanks for local Balham businesses, retail shops, offices, desks, and filing cabinets.',
      fullDescription: 'High precision duplicates for commercial premises, master suites, and office cabinetry.',
      icon: 'Building2',
      turnaround: '3 - 5 minutes',
      active: true,
      sortOrder: 4,
      features: ['Cabinet and locker keys', 'Commercial shutters & grilles', 'Bulk duplication orders'],
    },
    {
      id: 'svc-5',
      name: 'Replacement Keys',
      shortDescription: 'Keys cut from worn or damaged originals. We reconstruct key bitting profiles to restore smooth operation.',
      fullDescription: 'If your existing key is sticking in the lock barrel, we can cut a fresh key to exact original factory specs.',
      icon: 'Wrench',
      turnaround: '5 minutes',
      active: true,
      sortOrder: 5,
      features: ['Re-aligned tooth spacing', 'Removes sticky lock issues', 'Calibrated to original spec'],
    },
    {
      id: 'svc-6',
      name: 'Mortice & Chubb Keys',
      shortDescription: 'Heavy-duty traditional mortice deadlocks and lever keys cut on specialised bit-cutting equipment.',
      fullDescription: 'Experienced cutting of traditional 3-lever and 5-lever British Standard mortice deadlocks.',
      icon: 'ShieldCheck',
      turnaround: '5 - 10 minutes',
      active: true,
      sortOrder: 6,
      features: ['5-lever British Standard locks', 'Chubb and Union deadlocks', 'Hand-gauged bit tolerances'],
    },
    {
      id: 'svc-7',
      name: 'Additional Key Services',
      shortDescription: 'Specialist padlocks, garage door keys, window lock keys, and custom key accessories.',
      fullDescription: 'From shed padlocks to security chain keys, we carry hundreds of specialised key profiles.',
      icon: 'Lock',
      turnaround: '2 - 5 minutes',
      active: true,
      sortOrder: 7,
      features: ['Padlocks & sheds', 'Window restrictor keys', 'Keyrings & identification rings'],
    },
  ],
  openingHours: {
    schedule: [
      { day: 'Monday', dayIndex: 1, openTime: '08:30', closeTime: '18:00', isClosed: false },
      { day: 'Tuesday', dayIndex: 2, openTime: '08:30', closeTime: '18:00', isClosed: false },
      { day: 'Wednesday', dayIndex: 3, openTime: '08:30', closeTime: '18:00', isClosed: false },
      { day: 'Thursday', dayIndex: 4, openTime: '08:30', closeTime: '18:00', isClosed: false },
      { day: 'Friday', dayIndex: 5, openTime: '08:30', closeTime: '18:00', isClosed: false },
      { day: 'Saturday', dayIndex: 6, openTime: '09:00', closeTime: '17:30', isClosed: false },
      { day: 'Sunday', dayIndex: 0, openTime: '10:30', closeTime: '16:00', isClosed: false },
    ],
    holidayNotice: 'Bank holiday hours may vary slightly. Please call ahead to confirm holiday opening.',
  },
  testimonials: [
    {
      id: 'test-1',
      authorName: 'Oliver H.',
      location: 'Balham High Road',
      rating: 5,
      reviewText: 'Cut 3 front door keys in less than three minutes and every single one turned like butter in our Victorian rim lock. Fantastic local service.',
      serviceUsed: 'House Keys',
      date: 'March 2026',
      active: true,
    },
    {
      id: 'test-2',
      authorName: 'Sophie T.',
      location: 'Bedford Hill, Balham',
      rating: 5,
      reviewText: 'Our estate agent lost the spare mortice key. Came here on Saturday morning and had two perfect copies made straight away. Very friendly and knowledgeable.',
      serviceUsed: 'Mortice & Chubb Keys',
      date: 'February 2026',
      active: true,
    },
    {
      id: 'test-3',
      authorName: 'Mark W.',
      location: 'Nightingale Lane',
      rating: 5,
      reviewText: 'Quick, honest, and properly deburred keys. Much better quality than the automatic machines in big supermarkets.',
      serviceUsed: 'Key Duplication',
      date: 'January 2026',
      active: true,
    },
  ],
  googleReviews: {
    isConnected: false,
    rating: null,
    totalReviews: null,
    reviews: [],
    placeId: '',
  },
  seo: {
    homepageTitle: 'Balham Key Cutting | Fast & Reliable Key Duplication in Balham, London',
    metaDescription: 'Professional key cutting and key duplication services in Balham, London. Fast counter service for house keys, mortice keys, and commercial spares.',
    aboutTitle: 'About Balham Key Cutting | Local Key Specialists',
    servicesTitle: 'Key Cutting Services Balham | House, Mortice & Spares',
    contactTitle: 'Contact Balham Key Cutting | Get Directions & Enquire',
    defaultOgImage: '',
    googleAnalyticsId: '',
    googleSearchConsoleCode: '',
    canonicalBase: 'https://balhamkeycutting.co.uk',
  },
};
